# Variables and Flags
CC = gcc
CFLAGS = -Wall -g


# Target executable name
TARGET = pointers

# Default Target 
all: $(TARGET)

# Compile Executable
$(TARGET): pointers.c
		$(CC) $(CFLAGS) -o $(TARGET) pointers.c


# clean up
clean:
	rm -f $(TARGET)
